- name: Install Java 1.7 and some basic dependencies
  yum: name={{item}} state=present
  with_items:
   - unzip
   - jdk 
   - telnet
   - nc
   - wireshark
   - tcpdump 

- name: Install HTTPD
  yum: name={{item}} state=present
  with_items:
  - httpd
- name: stop httpd
  service: name=httpd state=started enabled=yes


- name: stop iptables
  service: name=iptables state=stopped enabled=no

- include: mapr_profile.yaml
- include: selinux.yml
